# Generated by Django 5.0.4 on 2026-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("price", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
